### ISSUE TITLE
Can't handle recursive data structures

### ISSUE THREAD

**Issue by apeiros** [ollie/deep_dup#1]
The following code:

```
a = [1,2,3]
a << a
DeepDup.deep_dup(a)
```

Produces the following error:

```
SystemStackError: stack level too deep
from /.../ruby-2.2.2/gems/deep_dup-0.0.1/lib/deep_dup.rb:39:in `block in deep_dup'
     /.../ruby-2.2.2/gems/deep_dup-0.0.1/lib/deep_dup.rb:39:in `map'
     /.../ruby-2.2.2/gems/deep_dup-0.0.1/lib/deep_dup.rb:39:in `deep_dup'
     /.../ruby-2.2.2/gems/deep_dup-0.0.1/lib/deep_dup.rb:39:in `block in deep_dup'
     /.../ruby-2.2.2/gems/deep_dup-0.0.1/lib/deep_dup.rb:39:in `map'
```

[edit: fixed markup]

**Comment by ollie** [comment]
Ok thanks, I'll try to fix it.

**Comment by ollie** [comment]
Fixed.
